const PUZZLES = ["apple", "breeze", "capture", "dinosaur", "grape", "silver", "rainbow", "treasure", "ocean", "yellow", "journey", "umbrella"];
const board=document.querySelector("#board"), 
statusMessage=document.querySelector("#game-status"), 
guessRule=document.querySelector("#guess-rule"), 
form=document.querySelector("#guess-form"), 
input=document.querySelector("#guess-input"), 
submitButton=document.querySelector("#guess-button"); 
let game;
function startGame(){const dayNumber=Math.floor(Date.now()/86400000),answer=PUZZLES[dayNumber%PUZZLES.length],length=answer.length;game={length,maxGuesses:length+1,answer,guesses:[],finished:false};input.maxLength=length;input.placeholder=`Type a ${length}-letter word`;input.value="";guessRule.textContent=`Today's puzzle has ${length} letters — you have ${length+1} guesses.`;setStatus(`${game.maxGuesses} guesses to find the word.`);render();input.focus()}
function setStatus(message,isError=false){statusMessage.textContent=message;statusMessage.classList.toggle("error",isError)}
function scoreGuess(guess,answer){const result=Array(game.length).fill("absent"),remaining=answer.split("");[...guess].forEach((letter,index)=>{if(letter===answer[index]){result[index]="correct";remaining[index]=null}});[...guess].forEach((letter,index)=>{if(result[index]!=="correct"){const match=remaining.indexOf(letter);if(match!==-1){result[index]="present";remaining[match]=null}}});return result}
function render(){board.replaceChildren();for(let rowIndex=0;rowIndex<game.maxGuesses;rowIndex++){const row=document.createElement("div");row.className="row";row.style.gridTemplateColumns=`repeat(${game.length},1fr)`;const guess=game.guesses[rowIndex];for(let index=0;index<game.length;index++){const cell=document.createElement("div");cell.className="cell";if(guess){cell.textContent=guess.word[index];cell.classList.add(guess.result[index])}row.append(cell)}board.append(row)}input.disabled=game.finished;submitButton.disabled=game.finished}
function submitGuess(){const guess=input.value.trim().toLowerCase();if(guess.length!==game.length||!/^[a-z]+$/.test(guess))return setStatus(`Enter exactly ${game.length} letters.`,true);const result=scoreGuess(guess,game.answer);game.guesses.push({word:guess,result});updateKeyStates(guess,result);input.value="";if(guess===game.answer){game.finished=true;setStatus(`Excellent — you found ${game.answer.toUpperCase()} in ${game.guesses.length} guess${game.guesses.length===1?"":"es"}!`)}else if(game.guesses.length===game.maxGuesses){game.finished=true;setStatus(`The word was ${game.answer.toUpperCase()}. Try another game!`)}else setStatus(`${game.maxGuesses-game.guesses.length} guesses left.`);render()}
form.addEventListener("submit",event=>{event.preventDefault();submitGuess()});input.addEventListener("input",()=>{input.value=input.value.replace(/[^a-z]/gi,"").toUpperCase()});startGame();
