const WORDS = { 5:["apple","beach","cabin","dream","flame","grape","house","ivory","jolly","lemon","mango","night","ocean","plant","queen","river","smile","tiger","ultra","vivid","whale","youth","zebra"], 6:["animal","breeze","candle","desert","engine","forest","garden","honest","island","jungle","kitten","little","magnet","nature","orange","puzzle","rabbit","silver","travel","unique","violet","window","yellow"], 7:["airport","balance","capture","diamond","evening","fortune","gallery","harvest","journey","kingdom","lantern","machine","notebook","outside","picture","quality","rainbow","station","thunder","unusual","victory","weather"], 8:["adventure","building","calendar","dinosaur","elephant","festival","hospital","interest","keyboard","language","mountain","painting","question","sandwich","treasure","umbrella","vacation","wildlife"] };
const board=document.querySelector("#board"), statusMessage=document.querySelector("#game-status"), form=document.querySelector("#guess-form"), input=document.querySelector("#guess-input"), submitButton=document.querySelector("#guess-button"), lengthSelect=document.querySelector("#word-length"), newGameButton=document.querySelector("#new-game"), keyboard=document.querySelector("#keyboard"); let game;
function startGame(){const length=Number(lengthSelect.value),words=WORDS[length];game={length,maxGuesses:length+1,answer:words[Math.floor(Math.random()*words.length)],guesses:[],finished:false,keyStates:{}};input.maxLength=length;input.placeholder=`Enter a ${length}-letter word`;input.value="";setStatus(`${game.maxGuesses} guesses to find a ${length}-letter word.`);render();input.focus()}
function setStatus(message,isError=false){statusMessage.textContent=message;statusMessage.classList.toggle("error",isError)}
function scoreGuess(guess,answer){const result=Array(game.length).fill("absent"),remaining=answer.split("");[...guess].forEach((letter,index)=>{if(letter===answer[index]){result[index]="correct";remaining[index]=null}});[...guess].forEach((letter,index)=>{if(result[index]!=="correct"){const match=remaining.indexOf(letter);if(match!==-1){result[index]="present";remaining[match]=null}}});return result}
function updateKeyStates(guess,result){const priority={absent:1,present:2,correct:3};[...guess].forEach((letter,index)=>{if(!game.keyStates[letter]||priority[result[index]]>priority[game.keyStates[letter]])game.keyStates[letter]=result[index]})}
function render(){board.replaceChildren();for(let rowIndex=0;rowIndex<game.maxGuesses;rowIndex++){const row=document.createElement("div");row.className="row";row.style.gridTemplateColumns=`repeat(${game.length},1fr)`;const guess=game.guesses[rowIndex];for(let index=0;index<game.length;index++){const cell=document.createElement("div");cell.className="cell";if(guess){cell.textContent=guess.word[index];cell.classList.add(guess.result[index])}row.append(cell)}board.append(row)}renderKeyboard();input.disabled=game.finished;submitButton.disabled=game.finished}
function renderKeyboard(){keyboard.replaceChildren();["QWERTYUIOP","ASDFGHJKL","ZXCVBNM"].forEach((letters,rowIndex)=>{const row=document.createElement("div");row.className="key-row";if(rowIndex===2)row.append(createKey("Enter","wide"));[...letters].forEach(letter=>row.append(createKey(letter)));if(rowIndex===2)row.append(createKey("⌫","wide"));keyboard.append(row)})}
function createKey(label,extraClass=""){const key=document.createElement("button");key.type="button";key.className=`key ${extraClass}`;key.textContent=label;if(label.length===1&&game.keyStates[label.toLowerCase()])key.classList.add(game.keyStates[label.toLowerCase()]);key.addEventListener("click",()=>useKey(label));return key}
function useKey(key){if(game.finished)return;if(key==="Enter")form.requestSubmit();else if(key==="⌫")input.value=input.value.slice(0,-1);else if(input.value.length<game.length)input.value+=key;input.focus()}
function submitGuess(){const guess=input.value.trim().toLowerCase();if(guess.length!==game.length||!/^[a-z]+$/.test(guess))return setStatus(`Enter exactly ${game.length} letters.`,true);const result=scoreGuess(guess,game.answer);game.guesses.push({word:guess,result});updateKeyStates(guess,result);input.value="";if(guess===game.answer){game.finished=true;setStatus(`Excellent — you found ${game.answer.toUpperCase()} in ${game.guesses.length} guess${game.guesses.length===1?"":"es"}!`)}else if(game.guesses.length===game.maxGuesses){game.finished=true;setStatus(`The word was ${game.answer.toUpperCase()}. Try another game!`)}else setStatus(`${game.maxGuesses-game.guesses.length} guesses left.`);render()}
form.addEventListener("submit",event=>{event.preventDefault();submitGuess()});input.addEventListener("input",()=>{input.value=input.value.replace(/[^a-z]/gi,"").toUpperCase()});document.addEventListener("keydown",event=>{if(event.key==="Enter"&&document.activeElement!==lengthSelect)return;if(/^[a-zA-Z]$/.test(event.key)){event.preventDefault();useKey(event.key.toUpperCase())}if(event.key==="Backspace"){event.preventDefault();useKey("⌫")}});newGameButton.addEventListener("click",startGame);lengthSelect.addEventListener("change",startGame);startGame();
